### ISSUE TITLE
KEY BOARD NOT WORK

### ISSUE THREAD

**Issue by huasheng-yue** [gustavklopp/pypiano#2]
键盘表和WAV文件对不上

**Comment by gustavklopp** [comment]
"The keyboard table and the WAV file are not aligned "
What do you mean?
Please use English, I don't speak Chinese.

**Comment by huasheng-yue** [comment]
1) some key not work. e,a,s,d,f,lsh,c,b,6,7,8 no sound. but space,F1,F2,F3,F4,Num_6 can sounds.
2) every keyboard set is not work. the octave is ataxic........

**Comment by huasheng-yue** [comment]
>

**Comment by huasheng-yue** [comment]
My keyboardlauot is just like:
[
'`','1','2','3','4','5','6','7','8','9','0','-','=','Bs'
'tab','q','w','e','r','t','y','u','i','o','p','[',']','\\',
'Ca','a','s','d','f','g','h','j','k','l',';','\'','En',
'lsh','z','x','c','v','b','n','m',',','.','/','rsh'
]
It's not work with the list as:
[
49,10,11,12,13,14,15,16,17,18,19,20,21,
23,24,25,26,27,28,29,30,31,32,33,
38,39,40,41,42,43,44,45,46,47,48,51,
50,94,52,53,54,55,56,57,58,59,60,61,62
]
I want to know  what kind of the numbers you select by?
Thank you for your replys.
Best Regards.
